disabled_rules:
 - colon
 - nesting
 - orphaned_doc_comment
 - todo
 - trailing_comma
 - trailing_whitespace
 - unused_optional_binding

line_length:
 warning: 200
 error: 300
 ignores_function_declarations: true
 ignores_comments: true
 ignores_urls: true
 
function_body_length:
 warning: 100
 error: 200

function_parameter_count:
 warning: 6
 error: 8

type_body_length:
 warning: 500
